export const DOCS_EN = [
  {
    id: 'd-overview',
    title_en: 'ProxyBox — Architecture overview',
    category_en: 'Getting started',
    body_en: [
      'ProxyBox is a distributed proxy system with two main components:',
      '',
      '• **Control plane** — the central server (the one you are accessing now). Manages users, billing, proxy provisioning, and pushes configuration to agents.',
      '• **Agent (node)** — runs on a real VM or server, listens on proxy ports, and routes traffic to the internet using its own IP.',
      '',
      'Every proxy you buy:',
      '1. Gets a unique port plus its own username and password',
      '2. Maps to one egress IP (a fixed IPv4 or a rotating IPv6 pool)',
      '3. Supports 4 protocols on the same port: HTTP CONNECT/GET, SOCKS5, HTTPS-proxy (TLS), and Trojan',
      '',
      '**You have two ways to use it**:',
      '• **Buy from the pool**: pay hourly, use our infrastructure (IPv4 datacenter or IPv6 /48 prefix).',
      '• **BYON (Bring Your Own Node)**: install the agent on your VM and create free proxies that run on it. You pay your VM provider directly — we just manage the software.',
      '',
      '**Single token**: every account gets a token in the format `usr_<id>_<hex>` that works for EVERYTHING — REST API, BYON agent install, SDK. Rotate it on /api-docs.'
    ].join('\n')
  },
  {
    id: 'd-byon',
    title_en: 'BYON — Free proxies on your own VM',
    category_en: 'Getting started',
    body_en: [
      '**BYON (Bring Your Own Node)** lets you install the ProxyBox agent on your own VM, VPS, or dedicated server and create FREE proxies that run on it.',
      '',
      '**Why is it free?**',
      'You rent the infrastructure (VM, bandwidth, IPv4/IPv6) from your own provider. We only supply the software (agent + control plane + UI). You still get the full feature set: 4 protocols, IPv6 rotation pool, anti-abuse caps, dashboard, and API.',
      '',
      '**How to get started**:',
      '1. Open the **ProxyBox Hub** page (in the sidebar)',
      '2. Copy the install command (Linux v4/v6 or Windows)',
      '3. Paste it on your VM — the agent enrolls into your account automatically',
      '4. Go to **Buy proxy** → **From my nodes** tab → create a free proxy',
      '',
      '**Minimum VM specs for ~1000 IPv6 proxies**:',
      '• 2-4 vCPU, 4-8 GB RAM, 1 Gbps NIC',
      '• Linux Ubuntu 20.04+ or Windows Server 2019+',
      '• Routed IPv6 prefix /64 or larger (default /64, set `PROXYHUB_IPV6_PREFIX_LEN=48` if your provider routes a /48)',
      '',
      '**Personal token**: this is your API key (format `usr_<id>_<hex>`). Rotate or revoke it from the docs page.'
    ].join('\n')
  },
  {
    id: 'd-getting-started',
    title_en: 'How does ProxyBox work?',
    category_en: 'Getting started',
    body_en: 'You buy IPv4 or IPv6 proxies by the hour. Each proxy is a dedicated port with its own username and password, supporting HTTP and SOCKS5 on the same port. Traffic flows through our multi-node infrastructure.'
  },
  {
    id: 'd-protocols',
    title_en: 'The 4 connection protocols — which one should I pick?',
    category_en: 'Using ProxyBox',
    body_en: [
      'Every proxy opens **two ports**: `port` (plain TCP) and `port+443` (TLS-wrapped).',
      '',
      'The **plain port** accepts two protocols via first-byte multiplexing:',
      '• **HTTP proxy** (CONNECT + GET) — universal; works with any browser, curl, or scraper.',
      '• **SOCKS5** (with user/pass) — native app support for TCP. UDP over SOCKS5 is also supported.',
      '',
      'The **TLS port** accepts two protocols via first-byte detection after the TLS handshake:',
      '• **HTTPS proxy** — the SwitchyOmega "HTTPS://" scheme. Enable "Allow insecure cert" because the cert is self-signed (per-node).',
      '• **Trojan** — TLS disguised as HTTPS, anti-DPI. Compatible apps: v2rayN (Windows), v2rayNG (Android), Shadowrocket (iOS), Clash Verge (macOS), Hiddify.',
      '',
      'The same username/password works for all four protocols. The "Connect" tab in /proxies provides ready-made URLs and QR codes for every protocol.'
    ].join('\n')
  },
  {
    id: 'd-caps',
    title_en: 'Three-layer anti-abuse caps',
    category_en: 'Using ProxyBox',
    body_en: [
      'Every proxy has 3 caps to protect the infrastructure and prevent any single user from hogging resources:',
      '',
      '• **Cap A — Max conns/proxy** (default 100): total concurrent connections per proxy. Exceeded → rejected.',
      '• **Cap B — Max conns/source IP** (default 60): prevents a single source IP from consuming all of Cap A, leaving room for a second device.',
      '• **Cap C — New conns/s/IP** (default 30): burst rate limit. Blocks 10k-in-1s flood / DoS attempts.',
      '',
      'Caps are aggregated across ALL 4 protocols — HTTP + SOCKS5 + Trojan + HTTPS-proxy. Reset every cap with the "Disconnect all" button in /proxies → Connect.',
      '',
      'Admins can change the global default at /admin/system/features → Anti-abuse tab. Premium plans may override caps per proxy.'
    ].join('\n')
  },
  {
    id: 'd-ipv4-vs-ipv6',
    title_en: 'What is the difference between IPv4 and IPv6?',
    category_en: 'Getting started',
    body_en: 'IPv4 gives you one fixed IP that works on any site. IPv6 provides a large pool and supports random rotation on every new connection — great for scraping and account farming. IPv6 proxies must resolve AAAA records for the target.'
  },
  {
    id: 'd-trial',
    title_en: 'How much trial credit do I get?',
    category_en: 'Billing',
    body_en: 'New accounts receive 50,000 VND in trial credit (configured by the admin). Enough to try out a few IPv4/IPv6 proxies for several hours.'
  },
  {
    id: 'd-auto-renew',
    title_en: 'Can I enable auto-renew?',
    category_en: 'Using ProxyBox',
    body_en: 'Yes. When placing an order, enable "auto-renew" — the system will deduct from your balance and extend in 24h increments. You can disable it any time from the order page.'
  },
  {
    id: 'd-rotate',
    title_en: 'How does IPv6 rotation work?',
    category_en: 'Using ProxyBox',
    body_en: 'When rotation is enabled, every new connection picks a random IP from the node\'s IPv6 pool. The pool can be as large as a /48 (2^80 IPs). Existing connections keep their original IP until they close.'
  },
  {
    id: 'd-payment',
    title_en: 'How do I pay?',
    category_en: 'Billing',
    body_en: 'We currently support Stripe (international cards). Bank transfer and crypto are coming soon. Top up your wallet first — buying proxies deducts directly from the wallet balance.'
  },
  {
    id: 'd-refund',
    title_en: 'What is the refund policy?',
    category_en: 'Billing',
    body_en: 'If you bought the wrong proxy within the first 30 minutes and used less than 100 MB of traffic, you get a full refund. After that, refunds are prorated by the hours already consumed.'
  },
  {
    id: 'd-api',
    title_en: 'Where is the API documentation?',
    category_en: 'API',
    body_en: 'Go to the "Account" page → "API key" tab to get your customer key. Base endpoint: `/api/v1/user/*`. Full documentation lives on the dedicated developer docs page.'
  },
  {
    id: 'd-self-host-intro',
    title_en: 'Meet ProxyBox — a free self-hosted IPv4/IPv6 proxy platform',
    category_en: 'Self-host (your own panel)',
    body_en: [
      'ProxyBox is a complete proxy SaaS platform, **free and open source**, that anyone can self-host on their own VPS to sell IPv4/IPv6 proxies to customers or use internally within a team.',
      '',
      '## What does ProxyBox solve?',
      '',
      'You want to sell IPv4 or IPv6 proxies but:',
      '- You don\'t want to rely on a third-party panel (your data sits on someone else\'s server).',
      '- You don\'t want to build everything from scratch (auth, billing, dashboard, agent, rotation, anti-abuse — a lot).',
      '- You don\'t have the budget to hire a dev team to build it internally.',
      '',
      'ProxyBox is **the answer** — a complete panel, one-line install, hosted on your VPS, where customers enroll into YOUR panel (data never leaves your servers).',
      '',
      '## High-level architecture',
      '',
      '```',
      '                         ┌──────────────────────────────────────┐',
      '                         │       YOUR VPS (admin panel)         │',
      '                         │     Ubuntu + Node 22 + nginx + SSL   │',
      '                         │                                      │',
      '                         │  ┌──────────────┐  ┌──────────────┐  │',
      '   Customer              │  │  Vue 3 SPA   │  │  REST API    │  │',
      '       │                 │  │ (dashboard)  │  │ /api/v1/user │  │',
      '       │   HTTPS         │  └──────┬───────┘  └──────┬───────┘  │',
      '       └──────────────►  │         │ same Node.js   │           │',
      '                         │         └─────process────┘           │',
      '                         │                 │                    │',
      '                         │     ┌───────────▼────────────┐       │',
      '                         │     │   config.json (state)  │       │',
      '                         │     │   SQLite (billing+log) │       │',
      '                         │     │   master.key (AES-GCM) │       │',
      '                         │     └───────────┬────────────┘       │',
      '                         │                 │                    │',
      '                         │      Long-poll + mTLS port 8788      │',
      '                         └─────────────────┼────────────────────┘',
      '                                           │',
      '              ┌────────────────────────────┼───────────────────────────┐',
      '              │                            │                           │',
      '       ┌──────▼──────┐            ┌────────▼────────┐         ┌────────▼────────┐',
      '       │  Node A     │            │   Node B        │         │  Node C (Hub)   │',
      '       │ (admin pool)│            │   (BYON)        │         │ (hourly VPS)    │',
      '       │ Rust agent  │            │  Rust agent     │         │  Rust agent     │',
      '       │             │            │ owned by user X │         │  auto-installed │',
      '       │ IPv4 + /48v6│            │  IPv6 /64       │         │ via Virtualizor │',
      '       └──────┬──────┘            └────────┬────────┘         └────────┬────────┘',
      '              │                            │                           │',
      '              │   listener :20000-29999    │     listener :20000+      │',
      '              │   HTTP/SOCKS5/Trojan/TLS   │                           │',
      '              ▼                            ▼                           ▼',
      '       Internet                     Internet                    Internet',
      '       (egress IPv4 or              (egress IPv6 from           (egress per',
      '        IPv6 from /48 pool)          customer pool)              plan family)',
      '```',
      '',
      '## Key features',
      '',
      '### Multi-protocol on a single port',
      '- HTTP CONNECT, HTTP GET-through, SOCKS5, HTTPS-proxy (TLS), and Trojan — all sharing the same port pair.',
      '- Customers pick whatever protocol they like without changing their proxy configuration.',
      '',
      '### IPv4 and IPv6 side by side',
      '- IPv4 datacenter: one fixed IP per proxy.',
      '- IPv6 routed /48: pool rotation, one egress IP per connection (sticky or rotating).',
      '- Strict family: IPv6 proxies resolve AAAA only — no v4 leakage. IPv4 proxies resolve A only.',
      '',
      '### Three ways to monetize ProxyBox',
      '- **A. Sell from a proxy pool** — you provide the VPS, install the agent, customers buy proxies by the hour.',
      '- **B. Hourly Hub VPS** — Virtualizor integration: customers rent a dedicated VPS and the agent is bootstrapped automatically over SSH.',
      '- **C. BYON (Bring Your Own Node)** — customers bring their own VPS, install the agent from your panel for FREE, and create proxies without spending wallet credit.',
      '',
      '### Security and anti-abuse',
      '- **mTLS** between agents and master (self-signed CA, one cert per node).',
      '- **scrypt** password hashing, **AES-256-GCM** encryption for every at-rest secret.',
      '- **TOTP 2FA** + admin IP allowlist + SQLite audit log.',
      '- **3-layer caps**: max conn/proxy, max conn/source IP, max new-conn/s/src.',
      '',
      '### Full remote control for admins',
      '- One click: reboot VPS, restart agent, diagnose (uptime/RAM/disk), tail logs.',
      '- Force-upgrade the agent binary (Linux + Windows built from your own panel).',
      '- Whitelisted package install (htop, iperf3, mtr…) via apt-get.',
      '- Drain mode and per-node token rotation.',
      '',
      '### Wallet and billing',
      '- VND/USD wallet, auto-renew proxies, tier discounts.',
      '- Coupon codes, partial/full refunds, per-transaction audit log.',
      '- Stripe integration (webhook signature verification + idempotency).',
      '- Raw-socket SMTP + Telegram alerts + outbound webhooks.',
      '',
      '### One-click self-upgrade',
      'Admin → Settings → System → click "Upgrade to latest version". The server runs `git pull` + `npm install` + `npm run build` + restart by itself. Around 60 seconds; customer traffic is NOT affected (TCP listeners stay live).',
      '',
      '## Three monetization flows — illustrated',
      '',
      '### A. Customer buys from the admin pool',
      '',
      '```',
      '   Customer               Panel (admin)            Admin node',
      '       │                       │                       │',
      '       │  1. Login + topup     │                       │',
      '       ├──────────────────────►│                       │',
      '       │                       │                       │',
      '       │  2. POST /orders      │                       │',
      '       │     type=ipv6, qty=5  │                       │',
      '       ├──────────────────────►│                       │',
      '       │                       │  3. pickZoneNode      │',
      '       │                       ├──────────────────────►│',
      '       │                       │  4. push proxy config │',
      '       │                       │   (port + user + pass)│',
      '       │                       │                       │',
      '       │  5. Return creds      │                       │',
      '       │◄──────────────────────┤                       │',
      '       │                                               │',
      '       │  6. Connect to proxy:                         │',
      '       │     curl -x http://user:pass@node-ip:port     │',
      '       ├──────────────────────────────────────────────►│',
      '       │                                       7. egress IPv6 from /48',
      '       │                                               │',
      '       │                              Internet ───────►│ target.com',
      '```',
      '',
      '### B. Hourly Hub VPS (via Virtualizor)',
      '',
      '```',
      '   Customer            Panel                 Virtualizor          New VPS',
      '       │                  │                     │                    │',
      '       │ 1. Buy hub plan  │                     │                    │',
      '       ├─────────────────►│                     │                    │',
      '       │                  │ 2. addvs API        │                    │',
      '       │                  │   (uid, RAM, OS,    │                    │',
      '       │                  │    IP pool)         │                    │',
      '       │                  ├────────────────────►│                    │',
      '       │                  │                     │ 3. Create VM       │',
      '       │                  │                     ├───────────────────►│',
      '       │                  │ 4. Wait for unlock  │                    │',
      '       │                  │   (poll vsDetail)   │                    │',
      '       │                  │                     │                    │',
      '       │                  │ 5. SSH bootstrap    │                    │',
      '       │                  │   curl install.sh   │                    │',
      '       │                  ├──────────────────────────────────────────►│',
      '       │                  │                                          │',
      '       │                  │ 6. Agent enrolls    ◄────────────────────│',
      '       │                  │   (claim placeholder)                    │',
      '       │                  │                                          │',
      '       │ 7. "Hub online"  │                                          │',
      '       │◄─────────────────┤                                          │',
      '       │                                                             │',
      '       │ 8. Create proxies on the hub (free, billing already paid)   │',
      '       ├────────────────────────────────────────────────────────────►│',
      '```',
      '',
      '### C. BYON — customer brings their own VPS',
      '',
      '```',
      '   Customer\'s VPS                       YOUR panel',
      '        │                                     │',
      '        │  1. SSH into the VPS and paste:     │',
      '        │     curl https://your-panel/        │',
      '        │       api/agent/install/usr_xxx     │',
      '        │       | sudo bash -s v4             │',
      '        │                                     │',
      '        │  2. Download binary from your panel │',
      '        │      (NEVER goes to a 3rd party)    │',
      '        ├────────────────────────────────────►│',
      '        │                                     │',
      '        │  3. Agent enrolls                   │',
      '        │     ownerId = customer.id           │',
      '        │     tag = "byon"                    │',
      '        ├────────────────────────────────────►│',
      '        │                                     │',
      '        │  4. Customer sees node in /my-nodes │',
      '        │◄────────────────────────────────────┤',
      '        │                                     │',
      '        │  5. /buy → "From my nodes" tab      │',
      '        │     create proxy FOR FREE           │',
      '        │     (only consumes a slot, no $)    │',
      '        │                                     │',
      '        │  6. Proxy runs on the customer VPS  │',
      '```',
      '',
      '## Security flow',
      '',
      '```',
      '   ┌──────────────┐    HTTPS (LE cert)    ┌──────────────┐',
      '   │   Browser    │ ─────────────────────►│    nginx     │',
      '   │   (admin /   │                       │  TLS 1.2/1.3 │',
      '   │   customer)  │                       │  :443        │',
      '   └──────────────┘                       └──────┬───────┘',
      '                                                 │ proxy_pass',
      '                                                 ▼ 127.0.0.1:8787',
      '   ┌────────────────────────────────────────────────────────────┐',
      '   │                  ProxyBox master process                   │',
      '   │                                                            │',
      '   │  Auth:                                                     │',
      '   │   • scrypt password hash                                   │',
      '   │   • Bearer token (60-min session)                          │',
      '   │   • Customer key usr_<id>_<hex> (160-bit, timing-safe)     │',
      '   │   • TOTP 2FA optional                                      │',
      '   │   • Admin IP allowlist                                     │',
      '   │                                                            │',
      '   │  Secrets at rest:                                          │',
      '   │   • master.key (32 bytes, chmod 600)                       │',
      '   │   • config.json secrets → AES-256-GCM v1: prefix           │',
      '   │     (SSH password, Virtualizor key, OAuth client_secret)   │',
      '   │                                                            │',
      '   │  Audit:                                                    │',
      '   │   • SQLite audit table (every admin action)                │',
      '   │   • SQLite conn_events (30-day retention)                  │',
      '   │   • Webhook fan-out (customer-defined)                     │',
      '   └────────────────────────────────────────────────────────────┘',
      '                              │',
      '                       mTLS  │  port 8788 (client cert auth)',
      '                              ▼',
      '   ┌────────────────────────────────────────────────────────────┐',
      '   │              Rust agent (each node, separate VPS)          │',
      '   │                                                            │',
      '   │  • Long-poll /api/agent/proxies?rev=N (25s)                │',
      '   │  • Heartbeat /api/agent/heartbeat (10s)                    │',
      '   │  • Strict family egress (IPv6 proxy = AAAA only)           │',
      '   │  • Per-proxy: bind IP, listen port, user/pass, rotation    │',
      '   │  • Anti-abuse: max-conn, bytes/sec, monthly quota          │',
      '   │  • Admin commands over heartbeat (BYON, no SSH needed)     │',
      '   └────────────────────────────────────────────────────────────┘',
      '```',
      '',
      '## One-line install',
      '',
      'A VPS running Ubuntu 22.04 / Debian 12, as root:',
      '',
      '```',
      'curl -fsSL https://proxybox.pro/install-panel.sh | sudo bash',
      '```',
      '',
      'The installer asks for 3 things:',
      '1. **Domain** — the hostname the panel will run on.',
      '2. **SSL** — Let\'s Encrypt (auto) / Self-signed / HTTP-only.',
      '3. **Admin** — defaults to `admin@admin.com` / `admin`.',
      '',
      'After 3-5 minutes (SPA build + Rust agent for Linux + Windows), the panel is live at `https://your-domain` — log in and change the password immediately.',
      '',
      '**Requirements**: 1 CPU / 1 GB RAM / 10 GB disk + a domain. For production we recommend 2 CPU / 2 GB RAM.',
      '',
      '## Tech stack',
      '',
      '- **Backend**: Node.js 22 monolith (~10k LOC), ZERO npm frameworks. Only `node:*` builtins + `ssh2` + `node-forge`.',
      '- **Frontend**: Vue 3 + Vite, lucide-vue-next, vue3-apexcharts. No Tailwind / no Vuetify — a pure CSS token system.',
      '- **Agent**: Rust + Tokio (proxy engine, mTLS, IPv6 strict family). Cross-built for Linux and Windows.',
      '- **Storage**: `config.json` (single-file state, ~120 KB) + SQLite (`billing_tx`, `audit`, `conn_events`). Atomic writes with WAL.',
      '- **PKI**: self-signed CA via `node-forge`, one client cert per agent.',
      '- **Stripe / SMTP / OAuth**: raw HTTPS / raw socket / raw OAuth flow — no SDKs.',
      '',
      '## Next steps',
      '',
      'Read the tabs below to install and configure:',
      '',
      '1. **[Self-host the panel](/faq#self-host-panel)** — full install command and options.',
      '2. **[Where customers enroll](/faq#self-host-customer-isolation)** — isolation explained.',
      '3. **[A→Z admin checklist](/faq#self-host-first-login)** — 10 steps right after install.',
      '4. **[Troubleshoot](/faq#self-host-troubleshoot)** — fixes for common errors.'
    ].join('\n')
  },
  {
    id: 'd-self-host',
    title_en: 'Self-host a ProxyBox panel on your own server',
    category_en: 'Self-host (your own panel)',
    body_en: [
      'You can **self-host your own ProxyBox panel** on your VPS — running fully independently, with no relationship to this panel. Your customers enroll their agents directly to your domain, so no data ever leaves your infrastructure.',
      '',
      '## Requirements',
      '',
      '- VPS with Ubuntu 22.04 / 24.04 (Debian 12 also works). 1 vCPU + 1 GB RAM + 10 GB disk for testing, 2 vCPU + 2 GB for production.',
      '- A domain pointing to your VPS IP (for HTTPS via Let\'s Encrypt). Without a domain you can still install — just run HTTP on the IP.',
      '- Root access.',
      '',
      '## One-line install',
      '',
      '```',
      'curl -fsSL https://proxybox.pro/install-panel.sh | sudo bash',
      '```',
      '',
      'The installer prompts for:',
      '1. **Domain** — panel hostname (e.g. `proxy.example.com`). Leave empty to use the IP.',
      '2. **SSL mode** — Let\'s Encrypt (recommended) / Self-signed / HTTP-only.',
      '3. **Admin email + password** — defaults to `admin@admin.com` / `admin`.',
      '',
      'After 3-5 minutes (SPA build + Rust agent), open `https://your-domain` → log in → **change the password immediately**.',
      '',
      '## Non-interactive (CI / Ansible)',
      '',
      '```',
      'curl -fsSL https://proxybox.pro/install-panel.sh | sudo bash -s -- \\',
      '  --domain proxy.example.com \\',
      '  --ssl letsencrypt \\',
      '  --admin-email me@example.com \\',
      '  --admin-pass \'StrongPw_1234!\' \\',
      '  --yes',
      '```',
      '',
      '## After install',
      '',
      '- **Change the admin password** immediately (Settings → Security).',
      '- **Enable 2FA** (TOTP) for the admin account.',
      '- **Set pricing** and **add zones** (Admin → Pricing / Zones).',
      '- **Disable registration** if it\'s an internal-only team (Admin → Features).',
      '- **Back up `server/master.key`** off-site — losing this file means losing every encrypted secret.',
      '',
      '## Upgrade to a new version',
      '',
      'Admin → **Settings → System** → click **Upgrade to latest version**. The backend runs `git pull` + rebuild + restart in about 60 seconds. Customer traffic is not affected.',
      '',
      '## Layout after install',
      '',
      '```',
      '/opt/proxyhub-free/',
      '  server/index.js           control plane',
      '  server/config.json        live state (chmod 600)',
      '  server/master.key         AES-256-GCM key (chmod 600)',
      '  server/data.db            SQLite: billing + audit + conn events',
      '  dist/                     Vue SPA build',
      '  rust-core/                Rust agent source + binary',
      '```',
      '',
      '## Operations',
      '',
      '- `systemctl status proxyhub` — service status',
      '- `journalctl -u proxyhub -f` — live log',
      '- `/etc/nginx/sites-available/proxyhub-free` — nginx config',
      '- `/etc/sudoers.d/proxyhub-free` — sudoers entry for self-upgrade',
      '',
      'Full details: see the [README on GitHub](https://github.com/proxyhub/free).'
    ].join('\n')
  },
  {
    id: 'd-self-host-customer-isolation',
    title_en: 'Which panel do my customers\' agents enroll into?',
    category_en: 'Self-host (your own panel)',
    body_en: [
      'Every self-hosted panel has `config.api.publicUrl` set during install (`--domain your-domain` flag on the installer).',
      '',
      'When YOUR customer copies the agent install command from YOUR panel (e.g. `/my-nodes` → "Install command"), the URL is generated dynamically:',
      '',
      '```',
      'curl -fsSL https://YOUR-DOMAIN/api/agent/claim/<token> | sudo bash -s v4',
      '```',
      '',
      '`YOUR-DOMAIN` is the domain you set at install time. The customer\'s agent will:',
      '- Download the binary from `https://YOUR-DOMAIN/api/agent/claim-binary/<token>`',
      '- Register the node at `https://YOUR-DOMAIN/api/agent/claim`',
      '- Heartbeat to `https://YOUR-DOMAIN/api/agent/heartbeat`',
      '',
      'It never contacts any other panel. Fully isolated.',
      '',
      '**To verify**: SSH into a VPS that already has the agent installed and inspect `/etc/proxybox-agent.json` — the `controlUrl` field must be your domain.'
    ].join('\n')
  },
  {
    id: 'd-self-host-first-login',
    title_en: 'Right after install — A→Z admin checklist',
    category_en: 'Self-host (your own panel)',
    body_en: [
      'Once `install.sh` finishes you have an empty panel and one default admin. Follow these steps in order to get the panel ready for production.',
      '',
      '## 1. Change the admin password + enable 2FA (5 min)',
      '',
      '1. Log in as `admin@admin.com` / `admin` for the first time.',
      '2. Go to **Settings → Security** → change the password (>= 12 characters, don\'t reuse `admin`).',
      '3. Enable **2FA (TOTP)**: scan the QR with Authy, Google Authenticator, or Bitwarden.',
      '4. (Optional, recommended) Add your IP to `config.api.adminIpWhitelist` so admin login is restricted to fixed IPs:',
      '   ```bash',
      '   sudo nano /opt/proxyhub-free/server/config.json',
      '   # Inside api: { "adminIpWhitelist": ["1.2.3.4", "5.6.7.8"] }',
      '   sudo systemctl restart proxyhub',
      '   ```',
      '',
      '## 2. Back up `master.key` right away (3 min)',
      '',
      '`server/master.key` encrypts EVERY secret in config.json (SSH passwords, Virtualizor API keys, OAuth secrets). Lose it and you lose everything.',
      '',
      '```bash',
      'sudo tar czf ~/proxyhub-keys-$(date +%F).tgz \\',
      '  /opt/proxyhub-free/server/master.key',
      'scp ~/proxyhub-keys-*.tgz user@other-machine:safe-place/',
      '# Or upload to Google Drive / pCloud / Bitwarden Send.',
      '```',
      '',
      'Set up a weekly full-config backup cron:',
      '',
      '```bash',
      'sudo crontab -e',
      '# Add:',
      '# 0 3 * * 0 BACKUP_PASS=YOUR_PASS /opt/proxyhub-free/scripts/backup.sh /var/backups/proxyhub',
      '```',
      '',
      '## 3. Set pricing and zones (10 min)',
      '',
      '1. **Admin → Pricing**: set the per-hour price for IPv4 and IPv6. Prices are in VND per hour per proxy. For example:',
      '   - IPv4: `416 VND/h` (~10k/day, ~300k/month)',
      '   - IPv6: `291 VND/h` (~7k/day, ~210k/month)',
      '   - Tiers: `>10 proxies −5%`, `>50 −10%`, `>100 −15%`',
      '',
      '2. **Admin → Zones**: create a zone per datacenter with nodes. For example:',
      '   - `vn-hcm` — Vietnam HCM (Asia/Ho_Chi_Minh)',
      '   - `us-east` — US East (America/New_York)',
      '   - `sg` — Singapore (Asia/Singapore)',
      '',
      '   Customers pick a zone during checkout → the server picks a node within that zone.',
      '',
      '## 4. Add your first node (BYON pattern)',
      '',
      'There are 3 ways to add a node — pick one:',
      '',
      '### Option A — Admin pool (SSH-managed)',
      '',
      'You own a VPS dedicated to selling proxies. The admin pushes the agent over SSH:',
      '',
      '1. Admin → **Nodes** → **Add node** → enter host + SSH user/password + family (ipv4/ipv6) + zone.',
      '2. Click **Install** → master SSHes into the VPS, runs the install one-liner, agent auto-enrolls.',
      '3. The node shows up in the list with `Diagnose`, `Reboot`, `Drain`, …',
      '',
      '### Option B — Fleet enrollment (zero-touch)',
      '',
      'You want to install many nodes at once:',
      '',
      '1. Admin → **Nodes** → click **Fleet token** → copy the token (rotatable any time).',
      '2. On each target VPS:',
      '   ```bash',
      '   curl -fsSL https://YOUR-DOMAIN/api/agent/install/<fleet-token> | sudo bash -s v4',
      '   ```',
      '3. The agent registers itself, auto-detects IP + zone, and shows up within ~30 seconds.',
      '',
      '### Option C — Customer BYON (self-install, free)',
      '',
      'Your customer has their own VPS and wants to run their own proxies on it:',
      '',
      '1. Customer logs in → **My Nodes** → copies the install command (which includes their personal token `usr_…`).',
      '2. Pastes it on their VPS.',
      '3. Their node shows up under **My Nodes** with `ownerId = customer.id`. Only they see it.',
      '4. Customer goes to **Buy → From my nodes** → creates FREE proxies running on their VPS.',
      '',
      '## 5. (Optional) Hub proxies via Virtualizor',
      '',
      'If you operate a Virtualizor panel to sell VPS by the hour:',
      '',
      '1. **Admin → Hubs → Virtualizor instances → New instance**:',
      '   - Label: panel name (`FPT VN`, `Hetzner DE`, …)',
      '   - Zone: `vn-hcm` / `us-east` / …',
      '   - Panel URL: `https://<your-vz>:4085`',
      '   - API key + API pass: from **Configuration → API Keys** in your VZ panel. NOTE: `adminapikey` + `adminapipass`, NOT the end-user API.',
      '',
      '2. **Hub plans → New plan**: pick the instance → dropdowns auto-fetch servers / plans / OS / IP pools from Virtualizor. Click to select instead of typing IDs.',
      '',
      '3. Set the price (e.g. 2,500 VND/h), family (`ipv4`/`ipv6`), and specs (CPU/RAM/Disk/IPv6 range).',
      '',
      '4. Customer visits `/buy?source=hub` → orders → master calls Virtualizor addvs → SSH-bootstraps the agent → node enrolls and adopts the placeholder.',
      '',
      '## 6. Configure OAuth (optional)',
      '',
      'Let customers log in with Google or GitHub:',
      '',
      '1. **Admin → OAuth** → enable a provider → fill in `clientId` + `clientSecret` from Google Cloud Console / GitHub Developer Settings.',
      '2. Redirect URI to set in Google/GitHub: `https://YOUR-DOMAIN/api/auth/oauth/google/callback`.',
      '3. Customers see "Sign in with Google/GitHub" buttons on the login page.',
      '',
      '## 7. Stripe / SMTP / Telegram (optional)',
      '',
      '- **Stripe** (card payments): Admin → Payment → enable Stripe → paste secret key + webhook secret. Webhook URL: `https://YOUR-DOMAIN/api/billing/stripe-webhook`.',
      '- **SMTP** (recovery emails + alerts): Admin → Email → set SMTP host/port/user/password. Supports STARTTLS or implicit TLS.',
      '- **Telegram alerts** (notify admin when a node goes offline or a proxy fails): Admin → Notifications → Telegram bot token + chat ID.',
      '',
      '## 8. Disable registration if private',
      '',
      'If the panel only serves an internal team (no public signups):',
      '',
      '1. **Admin → Features** → disable the `registration` toggle.',
      '2. Admins create users manually at **Admin → Users → Add user**.',
      '3. Customers can only log in if the admin has provisioned an account.',
      '',
      '## 9. Self-upgrade to new versions',
      '',
      'When a new release lands (or you push code to your fork):',
      '',
      '1. **Settings → System** → click **Upgrade to latest version**.',
      '2. The server runs `git pull` + `npm install` + `npm run build` + `systemctl restart proxyhub`.',
      '3. Takes about 1 minute. Customer proxy traffic is NOT affected (TCP listeners stay live).',
      '',
      'If you maintain your own fork: run `git remote set-url origin <your-fork>` inside `/opt/proxyhub-free/` so the self-upgrade pulls from your fork.',
      '',
      '## 10. Firewall + nginx hardening',
      '',
      '```bash',
      'sudo ufw allow 80/tcp     # nginx HTTP (LE renewal)',
      'sudo ufw allow 443/tcp    # nginx HTTPS (panel + customer API)',
      'sudo ufw allow 8788/tcp   # mTLS agent channel',
      'sudo ufw allow 20000:29999/tcp  # proxy ports (if you also serve LOCAL proxies on this server)',
      'sudo ufw deny 8787        # block direct master port — only nginx may proxy to it',
      'sudo ufw enable',
      '```',
      '',
      'Port 8788 (mTLS) must be open to the internet because agents connect directly (bypassing nginx, IP-based cert).',
      '',
      '## Final smoke test',
      '',
      '- [ ] Logging in with the new password + 2FA works',
      '- [ ] `curl https://YOUR-DOMAIN/api/health` returns `{"ok":true}`',
      '- [ ] `systemctl status proxyhub` shows `active (running)` with memory < 200 MB',
      '- [ ] `journalctl -u proxyhub -n 20` shows no red errors',
      '- [ ] `master.key` is backed up off-site',
      '- [ ] End-to-end customer flow: register → buy 1 proxy → connect → traffic egresses fine'
    ].join('\n')
  },
  {
    id: 'd-self-host-security',
    title_en: 'Security and trust — does the install script contain a backdoor?',
    category_en: 'Self-host (your own panel)',
    body_en: [
      'A fair question right before you `curl ... | sudo bash` a script from an unknown server. Here\'s the full disclosure.',
      '',
      '## TL;DR',
      '',
      'The install script **DOES NOT** open any back channel into your server. After install, your panel runs 100% independently — there is no mechanism that lets the script provider reach your machine.',
      '',
      '## What MY server sees when you `curl install-panel.sh`',
      '',
      '**Just one HTTP request**, logged into the `oss_downloads` table:',
      '- Your IP (last octet masked when displayed)',
      '- User-Agent (e.g. `curl/7.81.0`)',
      '- Referer (usually empty if you copy-paste)',
      '',
      'Nothing else. I gain no access to your machine from a single HTTP GET.',
      '',
      '## What install.sh DOES on your machine',
      '',
      '1. `apt-get install nodejs nginx certbot ...` — official Ubuntu/Debian packages from the apt repo.',
      '2. `useradd -r proxyhub` — creates an unprivileged system user.',
      '3. `npm install` + `npm run build` — installs Vue dependencies (pinned in `package-lock.json`).',
      '4. `cargo build --release` — compiles the Rust agent from source (the binary is NOT downloaded from my server).',
      '5. Generates a 32-byte random `master.key` ON YOUR MACHINE (never leaves it).',
      '6. Creates `config.json` with admin@admin.com + random tokens, generated LOCALLY.',
      '7. `certbot --nginx` — requests a Let\'s Encrypt cert (the request goes from your server to LE, not through me).',
      '8. `systemctl enable proxyhub` — registers the systemd unit.',
      '',
      '## What install.sh **DOES NOT** do',
      '',
      '- It does NOT SSH back to your machine (there are no credentials it could use).',
      '- It does NOT install anyone\'s SSH public key in `~/.ssh/authorized_keys`.',
      '- It does NOT open a reverse tunnel (`ssh -R`, ngrok, frp, autossh).',
      '- It does NOT create a phone-home cron job.',
      '- It does NOT add a root/sudo user for any external party.',
      '- It does NOT install telemetry or analytics SDKs.',
      '- It does NOT send `master.key` / config / data anywhere off-box.',
      '- It does NOT set firewall rules that grant special access.',
      '',
      '## Audit the script BEFORE running (recommended)',
      '',
      'Trust but verify. Here\'s how:',
      '',
      '```',
      '# 1. Download it instead of piping directly to bash',
      'curl -fsSL https://proxybox.pro/install-panel.sh -o install.sh',
      '',
      '# 2. Read it (518 lines, well commented)',
      'less install.sh',
      '',
      '# 3. Compare the hash with the GitHub release (if available)',
      'sha256sum install.sh',
      '# Cross-check: https://github.com/proxyhub/free/releases/.../install.sh.sha256',
      '',
      '# 4. Grep for suspicious patterns (result must be EMPTY)',
      'grep -E "ngrok|frp|autossh|nc -e|/dev/tcp|crontab.*curl|wget.*\\|sh" install.sh',
      '',
      '# 5. All clear — now run it',
      'sudo bash install.sh',
      '```',
      '',
      '## Self-upgrade — the critical trust channel',
      '',
      'Your panel has a **Settings → System → Upgrade to latest version** button. The logic is:',
      '',
      '```',
      'cd /opt/proxyhub-free',
      'git pull --ff-only        ← from which remote?',
      'npm install               ← from npmjs.org',
      'npm run build',
      'systemctl restart proxyhub',
      '```',
      '',
      '**The key question**: where does `git pull` pull from?',
      '',
      'Per install.sh:',
      '- If you installed via `--source-dir /path/to/local/tarball` → there is no git remote → upgrade FAILS with "not a git repo" → absolutely safe.',
      '- If you installed with `--git-repo https://github.com/proxyhub/free.git` → the remote points to the upstream GitHub fork → upgrades pull from there.',
      '- Default (no flag) → no `git clone` happens → upgrade FAILS.',
      '',
      '**Production recommendation**:',
      '1. **Fork the repo** into YOUR GitHub org.',
      '2. Install with `--git-repo https://github.com/YOUR-ORG/proxyhub-free.git`.',
      '3. You fully control the code your customers run. Review upstream changes via PR in your fork → merge → click upgrade.',
      '',
      '## Your trust model should be',
      '',
      '1. **Initial install**: you run the script once — you accept trusting the author at this single point.',
      '2. **After install**: panel + agent run code that already lives ON YOUR MACHINE. No callback to the author.',
      '3. **Updates**: only via a git remote you control. Fork it and you have 100% control.',
      '4. **Periodic audit**: `find /opt/proxyhub-free -newer /tmp/install-ts -type f` to spot anything that appeared unexpectedly.',
      '',
      '## Can YOUR customers leak anything about my panel?',
      '',
      'No. When your customer:',
      '- Downloads the agent: from `https://YOUR-PANEL/api/agent/claim-binary/...` (YOUR panel).',
      '- Enrolls: at `https://YOUR-PANEL/api/agent/claim` (YOUR panel).',
      '- Heartbeats: to `https://YOUR-PANEL/api/agent/heartbeat`.',
      '',
      'Verify on a customer VPS: `cat /etc/proxybox-agent.json` → the `controlUrl` field must be your domain, NOT `proxybox.pro` or any other third-party hostname.',
      '',
      '## Want more evidence?',
      '',
      '- **Read the source**: install.sh + server/index.js are plain JS/Bash, no obfuscation.',
      '- **Network audit**: after install, run `ss -tnp` to see outbound connections. Only nginx (443) + node (8787 listening + outbound API calls when CUSTOMERS purchase proxies).',
      '- **tcpdump**: `tcpdump -i any host proxybox.pro` → 0 packets after install.',
      '- **strace the agent**: `strace -f -e network proxybox-agent` → only connects to `your-domain:8788` (mTLS) and the outbound proxy targets your customers use.',
      '',
      '## If you\'re still cautious',
      '',
      '**Air-gapped install**: download the tarball, scp to the VPS, install with `--source-dir`. After the initial script download, there is zero HTTP traffic to my server:',
      '',
      '```',
      '# On a machine with internet:',
      'curl -fsSL https://proxybox.pro/install-panel.sh -o install.sh',
      'curl -fsSL https://github.com/proxyhub/free/archive/main.tar.gz -o proxyhub-free.tar.gz',
      '',
      '# Audit both files',
      'sha256sum install.sh proxyhub-free.tar.gz',
      '',
      '# Upload to the VPS via scp',
      'scp install.sh proxyhub-free.tar.gz root@your-vps:/root/',
      '',
      '# On the VPS:',
      'tar xzf proxyhub-free.tar.gz',
      'sudo bash install.sh --source-dir /root/proxyhub-free-main --domain your-domain',
      '```',
      '',
      'After this step your VPS NEVER talks to proxybox.pro again. Every future update requires you to upload a new tarball and rerun the installer.'
    ].join('\n')
  },
  {
    id: 'd-self-host-troubleshoot',
    title_en: 'Troubleshooting — common errors',
    category_en: 'Self-host (your own panel)',
    body_en: [
      '## "Service failed to start" during install',
      '',
      '```bash',
      'sudo journalctl -u proxyhub -n 50',
      '```',
      '',
      'Common errors:',
      '- **`master.key` missing** — reseed: `sudo /opt/proxyhub-free/install.sh --force-reseed --yes`',
      '- **Port 8787 already in use** — change `config.api.port` and restart',
      '- **Node 22 missing** — `sudo apt install nodejs-22` or rerun the installer',
      '',
      '## "Let\'s Encrypt rate-limited"',
      '',
      'LE caps you at 5 certs per week per domain. Reinstalling many times in one week → blocked.',
      '',
      'Workarounds:',
      '- Wait 7 days, OR',
      '- Use a staging cert (patch `install.sh` to add `--test-cert`), OR',
      '- Fall back to `--ssl selfsigned` (browser warning, but it works).',
      '',
      '## Agent won\'t enroll',
      '',
      '1. On the target VPS, run:',
      '   ```bash',
      '   sudo journalctl -u proxybox-agent -f',
      '   ```',
      '2. `HTTP 401 Unauthorized` → fleet token is wrong or revoked → admin rotates the token.',
      '3. `error sending request` → firewall blocks port 8788 on the master, OR the cert\'s IP SAN doesn\'t match — check `dig YOUR-DOMAIN` resolves to the master IP.',
      '4. `mTLS handshake fail` → rerun the install one-liner to fetch the latest CA cert.',
      '',
      '## Slow proxy traffic',
      '',
      '1. Test directly on the node:',
      '   ```bash',
      '   curl --max-time 10 -o /dev/null -w "%{speed_download}\\n" -x http://user:pass@host:port https://speed.cloudflare.com/__down?bytes=10000000',
      '   ```',
      '2. Speed < 5 MB/s → CPU bottleneck on the node (check `htop`) or VPS bandwidth limit.',
      '3. Latency > 200 ms when the target is nearby → slow DNS resolver. In `proxyDefaults` ensure `allowPrivateTargets: false` (already the default).',
      '',
      '## Customer says "can\'t connect"',
      '',
      '1. **Settings → System → Diagnose** their node (if it\'s BYON / Hub):',
      '   - `uptime` + `load` + `disk` + agent version + open listeners',
      '2. If the agent is dead → click **Restart agent**.',
      '3. If the listener for that proxy\'s port is missing → click **Diagnose** → check logs, restart the agent.',
      '4. If the node has been offline > 10 minutes → `nodeAutoDisableAfterMin` kicks in automatically → the customer sees the node disabled.',
      '',
      '## SQLite database too large',
      '',
      'After 6 months `data.db` can grow to ~500 MB due to `conn_events`. Cron job:',
      '',
      '```sql',
      '-- Reduce retention from 30 days to 7 days',
      'DELETE FROM conn_events WHERE ts < strftime("%s", "now", "-7 days") * 1000;',
      'VACUUM;',
      '```',
      '',
      'Or turn tracking off: set `proxyDefaults.recordConnEvents: false` in config.json.',
      '',
      '## Restore from a backup',
      '',
      '```bash',
      '# Stop the service before restoring (avoid overwriting a running instance)',
      'sudo systemctl stop proxyhub',
      'sudo BACKUP_PASS=YOUR_PASS bash /opt/proxyhub-free/scripts/restore.sh \\',
      '  /var/backups/proxyhub/proxyhub-XXXX.tar.gz.enc',
      'sudo systemctl start proxyhub',
      '```',
      '',
      '## Need more support?',
      '',
      '- GitHub Issues: https://github.com/proxyhub/free/issues',
      '- Local docs: see `/opt/proxyhub-free/README.md`',
      '- Live log: `sudo journalctl -u proxyhub -f --since "10 min ago"`'
    ].join('\n')
  }
]
